mode: deployment

config:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

  exporters:
    prometheusremotewrite:
      endpoint: "http://mimir-distributor.observability:8080/api/v1/push"
    otlp:
      endpoint: "tempo-distributor.observability:4317"
      tls:
        insecure: true
    loki:
      endpoint: "http://loki-gateway.observability:3100/loki/api/v1/push"

  processors:
    batch: {}

  service:
    pipelines:
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [prometheusremotewrite]

      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp]

      logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [loki]
