grafana:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

loki:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi
  persistence:
    enabled: false

tempo:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi
  persistence:
    enabled: false

mimir:
  ingester:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
  distributor:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
  querier:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
  queryFrontend:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
  storeGateway:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
  ruler:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi

promtail:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
