grafana:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

loki:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi
  persistence:
    enabled: false

tempo:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi
  persistence:
    enabled: false

mimir:
  config: |
    activity_tracker:
      filepath: /active-query-tracker/activity.log
    ingester:
      ring:
        zone_awareness_enabled: true

  activityTracker:
    enabled: true
      
  distributor:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi

  ingester:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi

  querier:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi

  queryFrontend:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi

  storeGateway:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi

  queryScheduler:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi

  ruler:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi

  minio:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi

promtail:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
