serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: observability-sa@vast-pad-464511-i5.iam.gserviceaccount.com

loki:
  storage:
    type: gcs
    bucketNames:
      chunks: loki-chunks-1
      ruler: loki-ruler-1
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: gcs
        schema: v13
        index:
          prefix: index_
          period: 24h
  memcached:
    chunk_cache:
      enabled: true
    results_cache:
      enabled: true
  serviceAccount:
    annotations:
      iam.gke.io/gcp-service-account: observability-sa@vast-pad-464511-i5.iam.gserviceaccount.com

mimir:
  structuredConfig:
    usage_stats:
      enabled: false
    limits:
      max_global_series_per_user: 10000000
      max_global_exemplars_per_user: 10000000
    common:
      storage:
        backend: gcs
    alertmanager_storage:
      gcs:
        bucket_name: mimir-alertmanager-1
    ruler_storage:
      gcs:
        bucket_name: mimir-ruler-1
    blocks_storage:
      backend: gcs
      gcs:
        bucket_name: mimir-blocks-1
  serviceAccount:
    annotations:
      iam.gke.io/gcp-service-account: observability-sa@vast-pad-464511-i5.iam.gserviceaccount.com

tempo:
  reportingEnabled: false
  storage:
    trace:
      backend: gcs
      gcs:
        bucket_name: tempo-13
  serviceAccount:
    annotations:
      iam.gke.io/gcp-service-account: observability-sa@vast-pad-464511-i5.iam.gserviceaccount.com
  ingester:
    persistence:
      enabled: true
  structuredConfig:
    compactor:
      retention:
        traces: 336h
    query_frontend:
      search:
        max_duration: 336h0m0s
  traces:
    otlp:
      grpc:
        enabled: true
      http:
        enabled: true

grafana:
  adminUser: admin
  adminPassword: yourpassword
  service:
    type: LoadBalancer
