mimir:
  structuredConfig:
    limits:
      max_series_per_user: 500000
    blocks_storage:
      backend: filesystem
      filesystem:
        dir: /data

  ingester:
    replicas: 2

  distributor:
    replicas: 2

  querier:
    replicas: 2

  query_frontend:
    replicas: 2

  store_gateway:
    replicas: 2

  ruler:
    enabled: true

  compactor:
    enabled: true

  alertmanager:
    enabled: true

  admin_api:
    enabled: true

  gateway:
    enabled: true

  serviceMonitor:
    enabled: true

  # Enables ingress or LoadBalancer if needed
  nginx:
    enabled: true
    service:
      type: ClusterIP  # Use LoadBalancer if you want external access
      port: 80
