global:
  replicas: 1
  extraEnvFrom:
    - secretRef:
        name: mimir-object-store

mimir:
  structuredConfig:
    multitenancy_enabled: false

    limits_config:
      ingestion_rate_strategy: global
      max_global_series_per_user: 1000000
      max_global_series_per_metric: 100000
      max_global_samples_per_user: 10000000
      max_label_name_length: 1024
      max_label_value_length: 2048
      max_labels_per_series: 30

    ingester:
      lifecycler:
        ring:
          replication_factor: 1

    storage:
      tsdb:
        dir: /data/tsdb

    blocks_storage:
      backend: s3
      s3:
        endpoint: minio.observability.svc.cluster.local:9000
        bucket_name: mimir
        access_key_id: admin
        secret_access_key: admin123
        insecure: true

  alertmanager:
    enabled: false

  ruler:
    enabled: false

  minio:
    enabled: true
    persistence:
      enabled: false
    accessKey: admin
    secretKey: admin123

  compactor:
    enabled: true

  store_gateway:
    enabled: true

  query_scheduler:
    enabled: true

  overrides_exporter:
    enabled: false

nginx:
  enabled: true
  image:
    repository: nginx
    tag: stable
  config:
    default: true
  service:
    type: LoadBalancer
