mimir:
  structuredConfig:
    multitenancy_enabled: false

    server:
      http_listen_port: 8080
      grpc_listen_port: 9095

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist

    memberlist:
      join_members:
        - mimir-gossip-ring

    schema:
      configs:
        - from: "2022-01-01"
          store: tsdb
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
          chunks:
            prefix: chunk_

    storage:
      tsdb:
        dir: /data/tsdb
      backend: filesystem
      filesystem:
        dir: /data

    limits_config:
      ingestion_rate_strategy: global
      ingestion_rate_limit: 500000
      ingestion_burst_size: 1000000
      max_label_name_length: 1024
      max_label_value_length: 2048
      max_labels_per_series: 30

    ruler:
      rule_path: /data/ruler
      alertmanager_url: http://localhost:9093

  replicas: 1
  alertmanager:
    enabled: true

  compactor:
    enabled: true

  minio:
    enabled: true

  store_gateway:
    enabled: true

  querier:
    replicas: 2

  query_frontend:
    replicas: 2

  query_scheduler:
    replicas: 2
