tempo:
  metricsGenerator:
    enabled: true

  traces:
    otlp:
      grpc:
        enabled: true
        endpoint: 0.0.0.0:4317
      http:
        enabled: true
        endpoint: 0.0.0.0:4318

  tempo:
    search:
      enabled: true

  server:
    http_listen_port: 3100

  ingester:
    replicas: 2

  distributor:
    replicas: 2

  compactor:
    enabled: true

  querier:
    replicas: 2

  query_frontend:
    replicas: 2

  serviceMonitor:
    enabled: true

  persistence:
    enabled: false  # set to true and use GCS if you want persistent trace storage

  gateway:
    enabled: true
    service:
      type: ClusterIP  # Change to LoadBalancer if needed
      port: 80
