apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: otel-demo
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      prometheusremotewrite:
        endpoint: http://mimir-distributor.observability:8080/api/v1/push

      otlp/tempo:
        endpoint: tempo-distributor.observability:4317
        tls:
          insecure: true

      loki:
        endpoint: http://loki-gateway.observability:3100/loki/api/v1/push
        tls:
          insecure: true

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheusremotewrite]

        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/tempo]

        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [loki]
